
samples:
  - name: "K1463_2216_h2"
    asm_fa: /project/logsdon_shared/projects/asm-repair/fa/K1463_2216_hifiasm.fa
    read_dir: "/project/logsdon_shared/data/platinum_genomes/data/pacbio_hifi/K1463_2216/"
    read_ext: "fastq.gz"
    region_bed: "/project/logsdon_shared/projects/asm-repair/fa/K1463_2216_ALR_regions.bed"

output_dir: "results/nucflag"
tmp_dir: "temp"
config_nucflag: "config/nucflag.toml"
ignore_regions: "config/nucflag_ignore.bed"
threads_aln: 8
mem_aln: 30
processes_nucflag: 12
mem_nucflag: 50
samtools_view_flag: 2308
