
manifest_asm: "https://raw.githubusercontent.com/human-pangenomics/hprc_intermediate_assembly/refs/heads/main/data_tables/assemblies_pre_release_v0.4.index.csv"
output_asm: "/project/logsdon_shared/data/HPRC/assemblies"
manifest_hifi: "https://raw.githubusercontent.com/human-pangenomics/hprc_intermediate_assembly/refs/heads/main/data_tables/sequencing_data/data_hifi_pre_release.index.csv"
output_hifi: "/project/logsdon_shared/data/HPRC/hifi"
manifest_rm: "https://raw.githubusercontent.com/human-pangenomics/hprc_intermediate_assembly/refs/heads/main/data_tables/annotation/repeat_masker/repeat_masker_bed_pre_release_v0.1.index.csv"
output_rm: "/project/logsdon_shared/data/HPRC/repeatmasker"

output_dir: "results/nucflag"
output_coverage: false
logs_dir: "logs/nucflag"
benchmarks_dir: "benchmarks/nucflag"
threads_aln: 8
mem_aln: 30G
processes_nucflag: 12
mem_nucflag: 50G
samtools_view_flag: 2308
