benchmarks_dir: benchmarks/nucflag
logs_dir: logs/nucflag
mem_aln: 30G
mem_nucflag: 50G
output_coverage: true
output_dir: results/nucflag
processes_nucflag: 12
samples:
- asm_dir: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/asm/HG00280
  asm_rgx: .*\.gz$
  config: config/nucflag.toml
  name: HG00280
  read_fofn: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/hifi/HG00280.fofn
- asm_dir: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/asm/HG02074
  asm_rgx: .*\.gz$
  config: config/nucflag.toml
  name: HG02074
  read_fofn: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/hifi/HG02074.fofn
- asm_dir: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/asm/HG02040
  asm_rgx: .*\.gz$
  config: config/nucflag.toml
  name: HG02040
  read_fofn: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/hifi/HG02040.fofn
- asm_dir: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/asm/NA18971
  asm_rgx: .*\.gz$
  config: config/nucflag.toml
  name: NA18971
  read_fofn: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/hifi/NA18971.fofn
- asm_dir: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/asm/NA18608
  asm_rgx: .*\.gz$
  config: config/nucflag.toml
  name: NA18608
  read_fofn: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/hifi/NA18608.fofn
- asm_dir: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/asm/HG00290
  asm_rgx: .*\.gz$
  config: config/nucflag.toml
  name: HG00290
  read_fofn: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/hifi/HG00290.fofn
- asm_dir: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/asm/HG01934
  asm_rgx: .*\.gz$
  config: config/nucflag.toml
  name: HG01934
  read_fofn: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/hifi/HG01934.fofn
- asm_dir: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/asm/HG04157
  asm_rgx: .*\.gz$
  config: config/nucflag.toml
  name: HG04157
  read_fofn: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/hifi/HG04157.fofn
- asm_dir: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/asm/HG01530
  asm_rgx: .*\.gz$
  config: config/nucflag.toml
  name: HG01530
  read_fofn: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/hifi/HG01530.fofn
- asm_dir: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/asm/HG01433
  asm_rgx: .*\.gz$
  config: config/nucflag.toml
  name: HG01433
  read_fofn: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/hifi/HG01433.fofn
- asm_dir: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/asm/NA20850
  asm_rgx: .*\.gz$
  config: config/nucflag.toml
  name: NA20850
  read_fofn: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/hifi/NA20850.fofn
- asm_dir: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/asm/HG04115
  asm_rgx: .*\.gz$
  config: config/nucflag.toml
  name: HG04115
  read_fofn: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/hifi/HG04115.fofn
- asm_dir: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/asm/HG00706
  asm_rgx: .*\.gz$
  config: config/nucflag.toml
  name: HG00706
  read_fofn: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/hifi/HG00706.fofn
- asm_dir: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/asm/NA20870
  asm_rgx: .*\.gz$
  config: config/nucflag.toml
  name: NA20870
  read_fofn: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/hifi/NA20870.fofn
- asm_dir: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/asm/HG02135
  asm_rgx: .*\.gz$
  config: config/nucflag.toml
  name: HG02135
  read_fofn: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/hifi/HG02135.fofn
- asm_dir: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/asm/HG01167
  asm_rgx: .*\.gz$
  config: config/nucflag.toml
  name: HG01167
  read_fofn: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/hifi/HG01167.fofn
- asm_dir: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/asm/HG03017
  asm_rgx: .*\.gz$
  config: config/nucflag.toml
  name: HG03017
  read_fofn: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/hifi/HG03017.fofn
- asm_dir: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/asm/NA21093
  asm_rgx: .*\.gz$
  config: config/nucflag.toml
  name: NA21093
  read_fofn: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/hifi/NA21093.fofn
# - asm_dir: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/asm/HG03492
#   asm_rgx: .*\.gz$
#   config: config/nucflag.toml
#   name: HG03492
#   read_fofn: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/hifi/HG03492.fofn
- asm_dir: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/asm/HG02083
  asm_rgx: .*\.gz$
  config: config/nucflag.toml
  name: HG02083
  read_fofn: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/hifi/HG02083.fofn
- asm_dir: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/asm/HG02647
  asm_rgx: .*\.gz$
  config: config/nucflag.toml
  name: HG02647
  read_fofn: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/hifi/HG02647.fofn
- asm_dir: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/asm/HG01255
  asm_rgx: .*\.gz$
  config: config/nucflag.toml
  name: HG01255
  read_fofn: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/hifi/HG01255.fofn
- asm_dir: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/asm/HG02027
  asm_rgx: .*\.gz$
  config: config/nucflag.toml
  name: HG02027
  read_fofn: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/hifi/HG02027.fofn
- asm_dir: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/asm/HG02056
  asm_rgx: .*\.gz$
  config: config/nucflag.toml
  name: HG02056
  read_fofn: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/hifi/HG02056.fofn
- asm_dir: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/asm/HG04160
  asm_rgx: .*\.gz$
  config: config/nucflag.toml
  name: HG04160
  read_fofn: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/hifi/HG04160.fofn
# - asm_dir: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/asm/NA18612
#   asm_rgx: .*\.gz$
#   config: config/nucflag.toml
#   name: NA18612
#   read_fofn: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/hifi/NA18612.fofn
samtools_view_flag: 2308
threads_aln: 8
