benchmarks_dir: benchmarks/nucflag
logs_dir: logs/nucflag
mem_aln: 30G
mem_nucflag: 50G
output_coverage: true
output_dir: results/nucflag
processes_nucflag: 12
samples:
- asm_dir: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/asm/HG02514
  asm_rgx: .*\.gz$
  config: config/nucflag.toml
  name: HG02514
  read_fofn: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/hifi/HG02514.fofn
- asm_dir: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/asm/HG02735
  asm_rgx: .*\.gz$
  config: config/nucflag.toml
  name: HG02735
  read_fofn: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/hifi/HG02735.fofn
- asm_dir: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/asm/HG03098
  asm_rgx: .*\.gz$
  config: config/nucflag.toml
  name: HG03098
  read_fofn: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/hifi/HG03098.fofn
- asm_dir: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/asm/HG01258
  asm_rgx: .*\.gz$
  config: config/nucflag.toml
  name: HG01258
  read_fofn: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/hifi/HG01258.fofn
- asm_dir: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/asm/NA18522
  asm_rgx: .*\.gz$
  config: config/nucflag.toml
  name: NA18522
  read_fofn: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/hifi/NA18522.fofn
- asm_dir: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/asm/HG02145
  asm_rgx: .*\.gz$
  config: config/nucflag.toml
  name: HG02145
  read_fofn: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/hifi/HG02145.fofn
- asm_dir: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/asm/HG01074
  asm_rgx: .*\.gz$
  config: config/nucflag.toml
  name: HG01074
  read_fofn: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/hifi/HG01074.fofn
- asm_dir: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/asm/HG00738
  asm_rgx: .*\.gz$
  config: config/nucflag.toml
  name: HG00738
  read_fofn: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/hifi/HG00738.fofn
- asm_dir: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/asm/HG03130
  asm_rgx: .*\.gz$
  config: config/nucflag.toml
  name: HG03130
  read_fofn: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/hifi/HG03130.fofn
- asm_dir: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/asm/HG04187
  asm_rgx: .*\.gz$
  config: config/nucflag.toml
  name: HG04187
  read_fofn: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/hifi/HG04187.fofn
- asm_dir: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/asm/HG04228
  asm_rgx: .*\.gz$
  config: config/nucflag.toml
  name: HG04228
  read_fofn: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/hifi/HG04228.fofn
- asm_dir: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/asm/NA19700
  asm_rgx: .*\.gz$
  config: config/nucflag.toml
  name: NA19700
  read_fofn: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/hifi/NA19700.fofn
- asm_dir: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/asm/HG01358
  asm_rgx: .*\.gz$
  config: config/nucflag.toml
  name: HG01358
  read_fofn: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/hifi/HG01358.fofn
- asm_dir: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/asm/HG00673
  asm_rgx: .*\.gz$
  config: config/nucflag.toml
  name: HG00673
  read_fofn: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/hifi/HG00673.fofn
- asm_dir: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/asm/NA20870
  asm_rgx: .*\.gz$
  config: config/nucflag.toml
  name: NA20870
  read_fofn: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/hifi/NA20870.fofn
- asm_dir: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/asm/HG01192
  asm_rgx: .*\.gz$
  config: config/nucflag.toml
  name: HG01192
  read_fofn: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/hifi/HG01192.fofn
- asm_dir: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/asm/NA18952
  asm_rgx: .*\.gz$
  config: config/nucflag.toml
  name: NA18952
  read_fofn: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/hifi/NA18952.fofn
- asm_dir: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/asm/NA18620
  asm_rgx: .*\.gz$
  config: config/nucflag.toml
  name: NA18620
  read_fofn: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/hifi/NA18620.fofn
- asm_dir: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/asm/HG02738
  asm_rgx: .*\.gz$
  config: config/nucflag.toml
  name: HG02738
  read_fofn: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/hifi/HG02738.fofn
- asm_dir: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/asm/NA19443
  asm_rgx: .*\.gz$
  config: config/nucflag.toml
  name: NA19443
  read_fofn: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/hifi/NA19443.fofn
- asm_dir: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/asm/NA20346
  asm_rgx: .*\.gz$
  config: config/nucflag.toml
  name: NA20346
  read_fofn: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/hifi/NA20346.fofn
- asm_dir: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/asm/HG02602
  asm_rgx: .*\.gz$
  config: config/nucflag.toml
  name: HG02602
  read_fofn: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/hifi/HG02602.fofn
- asm_dir: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/asm/HG01167
  asm_rgx: .*\.gz$
  config: config/nucflag.toml
  name: HG01167
  read_fofn: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/hifi/HG01167.fofn
- asm_dir: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/asm/HG02056
  asm_rgx: .*\.gz$
  config: config/nucflag.toml
  name: HG02056
  read_fofn: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/hifi/HG02056.fofn
samtools_view_flag: 2308
threads_aln: 8
