benchmarks_dir: benchmarks/nucflag
logs_dir: logs/nucflag
mem_aln: 30G
mem_nucflag: 50G
output_coverage: true
output_dir: results/nucflag
processes_nucflag: 12
samples:
- asm_dir: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/asm_hgsvc/grouped/HG03248
  asm_rgx: .*\.gz$
  config: config/nucflag.toml
  name: HG03248
  read_fofn: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/hifi_hgsvc/HG03248.fofn
- asm_dir: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/asm_hgsvc/grouped/NA19650
  asm_rgx: .*\.gz$
  config: config/nucflag.toml
  name: NA19650
  read_fofn: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/hifi_hgsvc/NA19650.fofn
- asm_dir: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/asm_hgsvc/grouped/HG00512
  asm_rgx: .*\.gz$
  config: config/nucflag.toml
  name: HG00512
  read_fofn: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/hifi_hgsvc/HG00512.fofn
- asm_dir: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/asm_hgsvc/grouped/NA19317
  asm_rgx: .*\.gz$
  config: config/nucflag.toml
  name: NA19317
  read_fofn: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/hifi_hgsvc/NA19317.fofn
- asm_dir: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/asm_hgsvc/grouped/HG02492
  asm_rgx: .*\.gz$
  config: config/nucflag.toml
  name: HG02492
  read_fofn: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/hifi_hgsvc/HG02492.fofn
- asm_dir: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/asm_hgsvc/grouped/NA19331
  asm_rgx: .*\.gz$
  config: config/nucflag.toml
  name: NA19331
  read_fofn: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/hifi_hgsvc/NA19331.fofn
- asm_dir: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/asm_hgsvc/grouped/HG03371
  asm_rgx: .*\.gz$
  config: config/nucflag.toml
  name: HG03371
  read_fofn: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/hifi_hgsvc/HG03371.fofn
- asm_dir: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/asm_hgsvc/grouped/HG03732
  asm_rgx: .*\.gz$
  config: config/nucflag.toml
  name: HG03732
  read_fofn: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/hifi_hgsvc/HG03732.fofn
- asm_dir: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/asm_hgsvc/grouped/HG02011
  asm_rgx: .*\.gz$
  config: config/nucflag.toml
  name: HG02011
  read_fofn: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/hifi_hgsvc/HG02011.fofn
- asm_dir: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/asm_hgsvc/grouped/HG02666
  asm_rgx: .*\.gz$
  config: config/nucflag.toml
  name: HG02666
  read_fofn: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/hifi_hgsvc/HG02666.fofn
- asm_dir: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/asm_hgsvc/grouped/HG03065
  asm_rgx: .*\.gz$
  config: config/nucflag.toml
  name: HG03065
  read_fofn: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/hifi_hgsvc/HG03065.fofn
- asm_dir: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/asm_hgsvc/grouped/HG00358
  asm_rgx: .*\.gz$
  config: config/nucflag.toml
  name: HG00358
  read_fofn: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/hifi_hgsvc/HG00358.fofn
- asm_dir: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/asm_hgsvc/grouped/HG03456
  asm_rgx: .*\.gz$
  config: config/nucflag.toml
  name: HG03456
  read_fofn: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/hifi_hgsvc/HG03456.fofn
- asm_dir: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/asm_hgsvc/grouped/NA18534
  asm_rgx: .*\.gz$
  config: config/nucflag.toml
  name: NA18534
  read_fofn: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/hifi_hgsvc/NA18534.fofn
- asm_dir: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/asm_hgsvc/grouped/HG01505
  asm_rgx: .*\.gz$
  config: config/nucflag.toml
  name: HG01505
  read_fofn: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/hifi_hgsvc/HG01505.fofn
- asm_dir: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/asm_hgsvc/grouped/HG01596
  asm_rgx: .*\.gz$
  config: config/nucflag.toml
  name: HG01596
  read_fofn: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/hifi_hgsvc/HG01596.fofn
- asm_dir: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/asm_hgsvc/grouped/NA19705
  asm_rgx: .*\.gz$
  config: config/nucflag.toml
  name: NA19705
  read_fofn: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/hifi_hgsvc/NA19705.fofn
- asm_dir: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/asm_hgsvc/grouped/HG00731
  asm_rgx: .*\.gz$
  config: config/nucflag.toml
  name: HG00731
  read_fofn: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/hifi_hgsvc/HG00731.fofn
- asm_dir: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/asm_hgsvc/grouped/HG02953
  asm_rgx: .*\.gz$
  config: config/nucflag.toml
  name: HG02953
  read_fofn: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/hifi_hgsvc/HG02953.fofn
- asm_dir: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/asm_hgsvc/grouped/NA18989
  asm_rgx: .*\.gz$
  config: config/nucflag.toml
  name: NA18989
  read_fofn: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/hifi_hgsvc/NA18989.fofn
- asm_dir: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/asm_hgsvc/grouped/HG03009
  asm_rgx: .*\.gz$
  config: config/nucflag.toml
  name: HG03009
  read_fofn: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/hifi_hgsvc/HG03009.fofn
- asm_dir: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/asm_hgsvc/grouped/NA19347
  asm_rgx: .*\.gz$
  config: config/nucflag.toml
  name: NA19347
  read_fofn: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/hifi_hgsvc/NA19347.fofn
- asm_dir: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/asm_hgsvc/grouped/NA19239
  asm_rgx: .*\.gz$
  config: config/nucflag.toml
  name: NA19239
  read_fofn: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/hifi_hgsvc/NA19239.fofn
- asm_dir: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/asm_hgsvc/grouped/NA19384
  asm_rgx: .*\.gz$
  config: config/nucflag.toml
  name: NA19384
  read_fofn: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/hifi_hgsvc/NA19384.fofn
- asm_dir: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/asm_hgsvc/grouped/HG01890
  asm_rgx: .*\.gz$
  config: config/nucflag.toml
  name: HG01890
  read_fofn: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/hifi_hgsvc/HG01890.fofn
- asm_dir: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/asm_hgsvc/grouped/HG00096
  asm_rgx: .*\.gz$
  config: config/nucflag.toml
  name: HG00096
  read_fofn: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/hifi_hgsvc/HG00096.fofn
- asm_dir: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/asm_hgsvc/grouped/NA20509
  asm_rgx: .*\.gz$
  config: config/nucflag.toml
  name: NA20509
  read_fofn: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/hifi_hgsvc/NA20509.fofn
- asm_dir: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/asm_hgsvc/grouped/HG02554
  asm_rgx: .*\.gz$
  config: config/nucflag.toml
  name: HG02554
  read_fofn: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/hifi_hgsvc/HG02554.fofn
- asm_dir: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/asm_hgsvc/grouped/HG01457
  asm_rgx: .*\.gz$
  config: config/nucflag.toml
  name: HG01457
  read_fofn: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/hifi_hgsvc/HG01457.fofn
samtools_view_flag: 2308
threads_aln: 8
