benchmarks_dir: benchmarks/nucflag
logs_dir: logs/nucflag
mem_aln: 30G
mem_nucflag: 50G
output_coverage: true
output_dir: results/nucflag
processes_nucflag: 12
samples:
- asm_dir: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/asm/HG02391
  asm_rgx: .*\.gz$
  config: config/nucflag.toml
  name: HG02391
  read_fofn: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/hifi/HG02391.fofn
- asm_dir: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/asm/HG03471
  asm_rgx: .*\.gz$
  config: config/nucflag.toml
  name: HG03471
  read_fofn: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/hifi/HG03471.fofn
- asm_dir: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/asm/HG02258
  asm_rgx: .*\.gz$
  config: config/nucflag.toml
  name: HG02258
  read_fofn: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/hifi/HG02258.fofn
- asm_dir: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/asm/HG00609
  asm_rgx: .*\.gz$
  config: config/nucflag.toml
  name: HG00609
  read_fofn: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/hifi/HG00609.fofn
- asm_dir: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/asm/HG01099
  asm_rgx: .*\.gz$
  config: config/nucflag.toml
  name: HG01099
  read_fofn: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/hifi/HG01099.fofn
- asm_dir: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/asm/HG01261
  asm_rgx: .*\.gz$
  config: config/nucflag.toml
  name: HG01261
  read_fofn: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/hifi/HG01261.fofn
- asm_dir: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/asm/HG01934
  asm_rgx: .*\.gz$
  config: config/nucflag.toml
  name: HG01934
  read_fofn: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/hifi/HG01934.fofn
- asm_dir: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/asm/HG02074
  asm_rgx: .*\.gz$
  config: config/nucflag.toml
  name: HG02074
  read_fofn: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/hifi/HG02074.fofn
- asm_dir: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/asm/NA19043
  asm_rgx: .*\.gz$
  config: config/nucflag.toml
  name: NA19043
  read_fofn: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/hifi/NA19043.fofn
- asm_dir: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/asm/HG00280
  asm_rgx: .*\.gz$
  config: config/nucflag.toml
  name: HG00280
  read_fofn: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/hifi/HG00280.fofn
- asm_dir: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/asm/HG00140
  asm_rgx: .*\.gz$
  config: config/nucflag.toml
  name: HG00140
  read_fofn: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/hifi/HG00140.fofn
- asm_dir: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/asm/HG02965
  asm_rgx: .*\.gz$
  config: config/nucflag.toml
  name: HG02965
  read_fofn: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/hifi/HG02965.fofn
- asm_dir: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/asm/NA19682
  asm_rgx: .*\.gz$
  config: config/nucflag.toml
  name: NA19682
  read_fofn: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/hifi/NA19682.fofn
- asm_dir: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/asm/HG03017
  asm_rgx: .*\.gz$
  config: config/nucflag.toml
  name: HG03017
  read_fofn: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/hifi/HG03017.fofn
- asm_dir: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/asm/HG01530
  asm_rgx: .*\.gz$
  config: config/nucflag.toml
  name: HG01530
  read_fofn: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/hifi/HG01530.fofn
- asm_dir: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/asm/NA21093
  asm_rgx: .*\.gz$
  config: config/nucflag.toml
  name: NA21093
  read_fofn: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/hifi/NA21093.fofn
- asm_dir: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/asm/HG03742
  asm_rgx: .*\.gz$
  config: config/nucflag.toml
  name: HG03742
  read_fofn: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/hifi/HG03742.fofn
- asm_dir: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/asm/NA20752
  asm_rgx: .*\.gz$
  config: config/nucflag.toml
  name: NA20752
  read_fofn: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/hifi/NA20752.fofn
- asm_dir: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/asm/HG01928
  asm_rgx: .*\.gz$
  config: config/nucflag.toml
  name: HG01928
  read_fofn: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/hifi/HG01928.fofn
- asm_dir: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/asm/NA18608
  asm_rgx: .*\.gz$
  config: config/nucflag.toml
  name: NA18608
  read_fofn: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/hifi/NA18608.fofn
- asm_dir: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/asm/HG04199
  asm_rgx: .*\.gz$
  config: config/nucflag.toml
  name: HG04199
  read_fofn: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/hifi/HG04199.fofn
- asm_dir: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/asm/HG03942
  asm_rgx: .*\.gz$
  config: config/nucflag.toml
  name: HG03942
  read_fofn: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/hifi/HG03942.fofn
- asm_dir: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/asm/HG00126
  asm_rgx: .*\.gz$
  config: config/nucflag.toml
  name: HG00126
  read_fofn: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/hifi/HG00126.fofn
- asm_dir: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/asm/NA18974
  asm_rgx: .*\.gz$
  config: config/nucflag.toml
  name: NA18974
  read_fofn: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/hifi/NA18974.fofn
- asm_dir: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/asm/HG02572
  asm_rgx: .*\.gz$
  config: config/nucflag.toml
  name: HG02572
  read_fofn: /project/logsdon_shared/projects/HPRC/Snakemake-NucFlag-HPRC-chrY/data/hifi/HG02572.fofn
samtools_view_flag: 2308
threads_aln: 8
